### ISSUE TITLE
Dataset link not working ？

### ISSUE THREAD

**Issue by ZhaoShengjian** [Yura52/tabular-dl-num-embeddings#5]
The dataset link you provided （https://www.dropbox.com/s/r0ef3ij3wl049gl/data.tar?dl=1）
doesn't seem to be able to be downloaded, can you check it for an update, thank you.

**Comment by Yura52** [comment]
The link from README works for me, so maybe the reason is that your machine cannot connect to DropBox for some reason?

**Comment by Yura52** [comment]
The same discussion is continuing [here](https://github.com/Yura52/tabular-dl-revisiting-models/issues/35).
