### ISSUE TITLE
Perform a simple prediction from the tuned and trained best model ?

### ISSUE THREAD

**Issue by manmeet3591** [Yura52/tabular-dl-num-embeddings#6]
How can I perform only prediction over a test data and save the output in a csv file ? Sorry if this is too basic a question.

**Comment by manmeet3591** [comment]
Thank you. Also, the following line 

    lib.dump_predictions(predictions, output)

seems to save the outputs. What is the path where this goes ?

**Comment by Yura52** [comment]
The path is `output / 'predictions.npz'` (see [this](https://github.com/Yura52/tabular-dl-num-embeddings/blob/88ffa9fe0f6bb0446464896937cef91fe944296d/lib/util.py#L170) for details). You can print `output` to see the content of this variable.

**Comment by manmeet3591** [comment]
Thank you
