### ISSUE TITLE
How to inverse normalize the predictions ?

### ISSUE THREAD

**Issue by manmeet3591** [Yura52/tabular-dl-num-embeddings#8]
I have run the code and have generated predictions.npz, the normalization I used was quantile with the toml file similar to california data performing regression. Can you please help me in inverse normalizing the predictions

**Comment by Yura52** [comment]
If I understand your question correctly, you need to load `y_info.pickle` (it is saved in the same output directory) and:
1. multiply the predictions by `y_info['std']`
2. add `y_info['mean']` to the predictions

Does this help?

**Comment by manmeet3591** [comment]
Thank you so much. It solves my problem.
