### ISSUE TITLE
data issue

### ISSUE THREAD

**Issue by Jacob-X** [Yura52/tabular-dl-num-embeddings#9]
Sorry to bother you, but i have met a data issue, i can't downlaod the data from dropbox. Could you upload the data to other online driver, such as google driver or others, please. Thanks.

**Comment by Yura52** [comment]
Will it work for you if we provide a temporary link and remove it after you download the data?

**Comment by Yura52** [comment]
Here is a temporary link that will expire in several days: [link](https://disk.yandex.ru/d/IagR-6ZSdCGNwA). Please, let us know if you can download the data.

**Comment by Jacob-X** [comment]
> 

Thanks for your kindly help! I have managed to download the data files.

**Comment by Coldfire93** [comment]
> Here is a temporary link that will expire in several days: <deleted>. Please, let us know if you can download the data.

Hi, could you provide the temporary download link? I can't downlaod the data from dropbox. 
Thanks~

**Comment by Yura52** [comment]
@Coldfire93 can you describe what the error looks like? Do you have any hypotheses why Dropbox is unavailable for you?

**Comment by Coldfire93** [comment]
> @Coldfire93 can you describe what the error looks like? Do you have any hypotheses why Dropbox is unavailable for you?

I can't visit the Dropbox website because of connection error. I want to refer to the content of info.json. Could you just provide the content of info.json?
